mode: data_preprocess
data_preprocess_args:
  window_size: 300
  overlap: 0.3
  label_path: '/public/lhy/data/data_classed_by_label_integrated/'
train_args:
  device: 0
  epoch: 100
  batch_size: 1024
  window_size: 300
  lr: 0.001
  model_name: attention_g.h5
  model: MSRLSTM
  datatype: SHL
  train_path: /public/lhy/data/npz/all_data_train_0.8_window_300_overlap_0.300000_no_smooth.npz
  validate_path: /public/lhy/data/npz/all_data_test_0.2_window_300_overlap_0.300000_no_smooth.npz
  model_args:
    cnn: [32, 3]
    lstm: [128, 36, 128]
    attention: [128, 128]
    fc: [128, 256, 512, 1024, 8]
    dropout: 0.2
    resnet:
      f: 3
      filters: [64, 128, 128, 128]
      kernel_sizes: [3, 2, 2, 4]
      s: 4
      p: 2





